spring.jpa.hibernate.ddl-auto: update
#spring.datasource.url: jdbc:mysql://localhost:3306/individu
#spring.datasource.username: dali1
#spring.datasource.password: password123
#spring.jpa.properties.hibernate.dialect:  org.hibernate.dialect.MySQL5Dialect
spring.jpa.show-sql: true

#H2 database
spring.datasource.url: jdbc:h2:mem:monster
spring.datasource.driverClassName: org.h2.Driver
spring.datasource.username: sa
spring.datasource.password: password
spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

# JWT properties
auth:
  jwt:
    token_alive: PT5M
    private-key-location: 'classpath:auth-gateway.key'
    public-key-location: 'classpath:auth-gateway.pub'
    issuer: 'monster-back'
    signing-key-type: 'RSA'

logging:
  level:
    org.springframework.security: DEBUG
